// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookprt.proto

package bookService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusType int32

const (
	StatusType_UNKNOWN           StatusType = 0
	StatusType_OP_SUCCESS        StatusType = 1
	StatusType_NOT_FOUND         StatusType = 2
	StatusType_DB_DOWN           StatusType = 3
	StatusType_DB_OPERATION_FAIL StatusType = 4
)

var StatusType_name = map[int32]string{
	0: "UNKNOWN",
	1: "OP_SUCCESS",
	2: "NOT_FOUND",
	3: "DB_DOWN",
	4: "DB_OPERATION_FAIL",
}

var StatusType_value = map[string]int32{
	"UNKNOWN":           0,
	"OP_SUCCESS":        1,
	"NOT_FOUND":         2,
	"DB_DOWN":           3,
	"DB_OPERATION_FAIL": 4,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{0}
}

type Book struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               []string `protobuf:"bytes,3,rep,name=author,proto3" json:"author,omitempty"`
	ShortDesc            string   `protobuf:"bytes,4,opt,name=shortDesc,proto3" json:"shortDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() []string {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetShortDesc() string {
	if m != nil {
		return m.ShortDesc
	}
	return ""
}

type AddBookRequest struct {
	BookInfo             *Book    `protobuf:"bytes,1,opt,name=bookInfo,proto3" json:"bookInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{1}
}

func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (m *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(m, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetBookInfo() *Book {
	if m != nil {
		return m.BookInfo
	}
	return nil
}

type AddBookResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{2}
}

func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (m *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(m, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddBookResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetBookRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBookResponse struct {
	Status               StatusType `protobuf:"varint,1,opt,name=status,proto3,enum=bookService.StatusType" json:"status,omitempty"`
	Books                []*Book    `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{4}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetStatus() StatusType {
	if m != nil {
		return m.Status
	}
	return StatusType_UNKNOWN
}

func (m *GetBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *GetBookResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Review struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score                uint32   `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{5}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Review) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Review) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type AddReviewRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Review               *Review  `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReviewRequest) Reset()         { *m = AddReviewRequest{} }
func (m *AddReviewRequest) String() string { return proto.CompactTextString(m) }
func (*AddReviewRequest) ProtoMessage()    {}
func (*AddReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{6}
}

func (m *AddReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReviewRequest.Unmarshal(m, b)
}
func (m *AddReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReviewRequest.Marshal(b, m, deterministic)
}
func (m *AddReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReviewRequest.Merge(m, src)
}
func (m *AddReviewRequest) XXX_Size() int {
	return xxx_messageInfo_AddReviewRequest.Size(m)
}
func (m *AddReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddReviewRequest proto.InternalMessageInfo

func (m *AddReviewRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddReviewRequest) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type AddReviewResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReviewResponse) Reset()         { *m = AddReviewResponse{} }
func (m *AddReviewResponse) String() string { return proto.CompactTextString(m) }
func (*AddReviewResponse) ProtoMessage()    {}
func (*AddReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{7}
}

func (m *AddReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReviewResponse.Unmarshal(m, b)
}
func (m *AddReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReviewResponse.Marshal(b, m, deterministic)
}
func (m *AddReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReviewResponse.Merge(m, src)
}
func (m *AddReviewResponse) XXX_Size() int {
	return xxx_messageInfo_AddReviewResponse.Size(m)
}
func (m *AddReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddReviewResponse proto.InternalMessageInfo

func (m *AddReviewResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddReviewResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetReviewRequest struct {
	BookId               uint32   `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewRequest) Reset()         { *m = GetReviewRequest{} }
func (m *GetReviewRequest) String() string { return proto.CompactTextString(m) }
func (*GetReviewRequest) ProtoMessage()    {}
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{8}
}

func (m *GetReviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewRequest.Unmarshal(m, b)
}
func (m *GetReviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewRequest.Marshal(b, m, deterministic)
}
func (m *GetReviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewRequest.Merge(m, src)
}
func (m *GetReviewRequest) XXX_Size() int {
	return xxx_messageInfo_GetReviewRequest.Size(m)
}
func (m *GetReviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewRequest proto.InternalMessageInfo

func (m *GetReviewRequest) GetBookId() uint32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetReviewResponse struct {
	Status               StatusType `protobuf:"varint,1,opt,name=status,proto3,enum=bookService.StatusType" json:"status,omitempty"`
	Reviews              []*Review  `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetReviewResponse) Reset()         { *m = GetReviewResponse{} }
func (m *GetReviewResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewResponse) ProtoMessage()    {}
func (*GetReviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19cf54fba2a1c378, []int{9}
}

func (m *GetReviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewResponse.Unmarshal(m, b)
}
func (m *GetReviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewResponse.Merge(m, src)
}
func (m *GetReviewResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewResponse.Size(m)
}
func (m *GetReviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewResponse proto.InternalMessageInfo

func (m *GetReviewResponse) GetStatus() StatusType {
	if m != nil {
		return m.Status
	}
	return StatusType_UNKNOWN
}

func (m *GetReviewResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *GetReviewResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("bookService.StatusType", StatusType_name, StatusType_value)
	proto.RegisterType((*Book)(nil), "bookService.book")
	proto.RegisterType((*AddBookRequest)(nil), "bookService.addBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "bookService.addBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "bookService.getBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "bookService.getBookResponse")
	proto.RegisterType((*Review)(nil), "bookService.review")
	proto.RegisterType((*AddReviewRequest)(nil), "bookService.addReviewRequest")
	proto.RegisterType((*AddReviewResponse)(nil), "bookService.addReviewResponse")
	proto.RegisterType((*GetReviewRequest)(nil), "bookService.getReviewRequest")
	proto.RegisterType((*GetReviewResponse)(nil), "bookService.getReviewResponse")
}

func init() { proto.RegisterFile("bookprt.proto", fileDescriptor_19cf54fba2a1c378) }

var fileDescriptor_19cf54fba2a1c378 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x93, 0x7e, 0xd0, 0x5b, 0xb5, 0x4b, 0xcd, 0x18, 0xd1, 0x18, 0xa8, 0xf2, 0x03, 0x54,
	0x43, 0x1b, 0x52, 0x79, 0x44, 0x08, 0xb5, 0xeb, 0x3a, 0x55, 0x6c, 0xc9, 0xe4, 0xb6, 0xe2, 0x05,
	0x29, 0x64, 0x8d, 0xc9, 0xaa, 0xd1, 0xba, 0xc4, 0xee, 0x80, 0x07, 0x1e, 0xf9, 0x51, 0xfc, 0x3b,
	0x64, 0x3b, 0xe9, 0x92, 0xac, 0x3c, 0xc0, 0x9b, 0x6f, 0xef, 0xf1, 0x39, 0xc7, 0xf7, 0xdc, 0x14,
	0x1a, 0x57, 0x8c, 0xdd, 0xac, 0x22, 0x71, 0xbc, 0x8a, 0x98, 0x60, 0xa8, 0x2e, 0xcb, 0x31, 0x8d,
	0x6e, 0xe7, 0x33, 0x8a, 0x3f, 0x41, 0x49, 0x96, 0xa8, 0x09, 0xc6, 0x28, 0xb0, 0x8b, 0xed, 0x62,
	0xa7, 0x41, 0x8c, 0x51, 0x80, 0x10, 0x94, 0x96, 0xfe, 0x82, 0xda, 0x46, 0xbb, 0xd8, 0xa9, 0x11,
	0x75, 0x46, 0x7b, 0x50, 0xf1, 0xd7, 0xe2, 0x9a, 0x45, 0xb6, 0xd9, 0x36, 0x3b, 0x35, 0x12, 0x57,
	0xe8, 0x00, 0x6a, 0xfc, 0x9a, 0x45, 0x62, 0x40, 0xf9, 0xcc, 0x2e, 0xa9, 0x0b, 0x77, 0x3f, 0xe0,
	0x77, 0xd0, 0xf4, 0x83, 0xa0, 0xcf, 0xd8, 0x0d, 0xa1, 0x5f, 0xd7, 0x94, 0x0b, 0x74, 0x04, 0x0f,
	0xa4, 0xe6, 0x68, 0xf9, 0x99, 0x29, 0xc5, 0x7a, 0xb7, 0x75, 0x9c, 0xf2, 0xa4, 0xce, 0x64, 0x03,
	0xc1, 0x6f, 0x60, 0x67, 0x43, 0xc0, 0x57, 0x6c, 0xc9, 0x95, 0x13, 0x2e, 0x7c, 0xb1, 0xe6, 0xea,
	0x7e, 0x99, 0xc4, 0x15, 0xb2, 0xc0, 0x5c, 0xf0, 0x30, 0x36, 0x2d, 0x8f, 0xf8, 0x39, 0x34, 0x43,
	0x2a, 0xd2, 0xea, 0xbb, 0x50, 0xfe, 0x32, 0x5f, 0xcc, 0x45, 0x7c, 0x55, 0x17, 0xf8, 0x27, 0xec,
	0x6c, 0x70, 0xb1, 0xc8, 0xab, 0x8c, 0x48, 0xb3, 0xfb, 0x38, 0x63, 0x52, 0xb7, 0x26, 0x3f, 0x56,
	0x74, 0xa3, 0xfe, 0x02, 0xca, 0x12, 0xc1, 0x6d, 0xa3, 0x6d, 0x6e, 0x7f, 0x94, 0xee, 0x4b, 0x9b,
	0x17, 0x3c, 0xb4, 0x4d, 0x6d, 0xf3, 0x82, 0x87, 0x78, 0x08, 0x95, 0x88, 0xde, 0xce, 0xe9, 0xb7,
	0xad, 0x83, 0xdf, 0x85, 0x32, 0x9f, 0xb1, 0x88, 0xaa, 0x1b, 0x0d, 0xa2, 0x0b, 0x89, 0x14, 0xf4,
	0xbb, 0x88, 0x27, 0xae, 0xce, 0xd8, 0x05, 0xcb, 0x0f, 0x02, 0xa2, 0xa8, 0x92, 0x07, 0xe7, 0xa3,
	0x7d, 0x99, 0x68, 0x29, 0x8d, 0x7a, 0xf7, 0x61, 0xc6, 0xa7, 0x6e, 0x91, 0x18, 0x82, 0xdf, 0x42,
	0x2b, 0x45, 0xf8, 0xcf, 0xe3, 0x3f, 0x04, 0x2b, 0xa4, 0x22, 0xeb, 0x67, 0x0f, 0x2a, 0x2a, 0xdb,
	0xc4, 0x53, 0x5c, 0xe1, 0x5f, 0x45, 0x68, 0xa5, 0xc0, 0xff, 0x9b, 0xc2, 0x11, 0x54, 0xb5, 0xf7,
	0x24, 0x87, 0xad, 0xef, 0x4b, 0x30, 0xf7, 0xb3, 0x38, 0xfc, 0x08, 0x70, 0x47, 0x8b, 0xea, 0x50,
	0x9d, 0x3a, 0xef, 0x1d, 0xf7, 0x83, 0x63, 0x15, 0x50, 0x13, 0xc0, 0xbd, 0xf4, 0xc6, 0xd3, 0x93,
	0x93, 0xd3, 0xf1, 0xd8, 0x2a, 0xa2, 0x06, 0xd4, 0x1c, 0x77, 0xe2, 0x0d, 0xdd, 0xa9, 0x33, 0xb0,
	0x0c, 0x89, 0x1d, 0xf4, 0xbd, 0x81, 0xc4, 0x9a, 0xe8, 0x11, 0xb4, 0x06, 0x7d, 0xcf, 0xbd, 0x3c,
	0x25, 0xbd, 0xc9, 0xc8, 0x75, 0xbc, 0x61, 0x6f, 0x74, 0x6e, 0x95, 0xba, 0xbf, 0x0d, 0x48, 0x7f,
	0x80, 0x68, 0x08, 0xd5, 0x9e, 0xde, 0x6e, 0xf4, 0x24, 0x63, 0x34, 0xfb, 0xd1, 0xec, 0x1f, 0x6c,
	0x6f, 0xea, 0x29, 0xe1, 0x82, 0xe4, 0x39, 0xd3, 0x0b, 0x9c, 0xe3, 0xc9, 0xae, 0x7f, 0x8e, 0x27,
	0xb7, 0xf3, 0xb8, 0x80, 0xce, 0xa1, 0xd6, 0x4b, 0x02, 0x47, 0x4f, 0xf3, 0xa2, 0x99, 0x24, 0xf7,
	0x9f, 0xfd, 0xad, 0x9d, 0x66, 0x3b, 0x4b, 0x22, 0xcd, 0xb1, 0xe5, 0xf7, 0x22, 0xc7, 0x76, 0x6f,
	0x13, 0x70, 0xe1, 0xaa, 0xa2, 0xfe, 0xc0, 0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x26, 0x9b,
	0x39, 0x2e, 0xd1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	AddReview(ctx context.Context, in *AddReviewRequest, opts ...grpc.CallOption) (*AddReviewResponse, error)
	GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, "/bookService.bookService/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/bookService.bookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) AddReview(ctx context.Context, in *AddReviewRequest, opts ...grpc.CallOption) (*AddReviewResponse, error) {
	out := new(AddReviewResponse)
	err := c.cc.Invoke(ctx, "/bookService.bookService/AddReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error) {
	out := new(GetReviewResponse)
	err := c.cc.Invoke(ctx, "/bookService.bookService/GetReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	AddReview(context.Context, *AddReviewRequest) (*AddReviewResponse, error)
	GetReview(context.Context, *GetReviewRequest) (*GetReviewResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) AddBook(ctx context.Context, req *AddBookRequest) (*AddBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (*UnimplementedBookServiceServer) GetBook(ctx context.Context, req *GetBookRequest) (*GetBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookServiceServer) AddReview(ctx context.Context, req *AddReviewRequest) (*AddReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReview not implemented")
}
func (*UnimplementedBookServiceServer) GetReview(ctx context.Context, req *GetReviewRequest) (*GetReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReview not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookService.bookService/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookService.bookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_AddReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).AddReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookService.bookService/AddReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).AddReview(ctx, req.(*AddReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookService.bookService/GetReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetReview(ctx, req.(*GetReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookService.bookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookService_AddBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "AddReview",
			Handler:    _BookService_AddReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _BookService_GetReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookprt.proto",
}
